//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public string appointmentID { get; set; }
        public Nullable<System.DateTime> appointmentDate { get; set; }
        public Nullable<System.TimeSpan> appointmentTime { get; set; }
        public string apointmentPurpose { get; set; }
        public string patientID { get; set; }
        public string staffID { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
