//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string staffID { get; set; }
        public System.DateTime workingDate { get; set; }
        public System.TimeSpan checkInTime { get; set; }
        public System.TimeSpan checkOutTime { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
