//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitRecord
    {
        public string visitID { get; set; }
        public System.DateTime dateVisit { get; set; }
        public string status { get; set; }
        public string diagnosis { get; set; }
        public string medicineGiven { get; set; }
        public string dentistVisited { get; set; }
        public int roomNo { get; set; }
        public int totalVisit { get; set; }
        public int patientID { get; set; }
    }
}
